default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^(?:tests|scripts)/.*\.(md|py|ps1|sh)$|^(?:requirements-dev\.txt|\.pre-commit-config\.yaml)$
      - id: end-of-file-fixer
        files: ^(?:tests|scripts)/.*\.(md|py|ps1|sh)$|^(?:requirements-dev\.txt|\.pre-commit-config\.yaml)$
      - id: check-yaml
        files: ^\.pre-commit-config\.yaml$
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        files: ^(?:tests|scripts)/.*\.(md|py|ps1|sh)$|^(?:requirements-dev\.txt|\.pre-commit-config\.yaml|\.secrets\.baseline)$
